# Generated by Django 5.2 on 2025-04-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="calories",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_src",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit_name",
            field=models.TextField(blank=True, default=""),
        ),
    ]
