# Generated by Django 5.2 on 2025-04-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_product_calories_alter_product_image_src_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.JSONField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="instructions",
            field=models.TextField(blank=True, default=""),
        ),
    ]
