# Generated by Django 5.2 on 2025-04-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_recipe_ingredients_alter_recipe_instructions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
